Repository iterative/dvc-data, pull requests merged in 2023-01, with the labels that each got.

#251 meta: don't use slower asdict
  src/dvc_data/hashfile/meta.py
Labels: enhancement

#273 deps: bump dvc-objects to 0.18.2
  setup.cfg
Labels: maintenance

#279 index.diff: check for not None instead of boolean check which calls _…
  src/dvc_data/index/diff.py
Labels: perf
